modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
#issueTrackerURL="https://github.com/antiphysika/Initium/issues"

[[mods]]
  modId="${mod_id}"
  version="${mod_version}"
  displayName="${mod_name}"
  #updateJSONURL="https://raw.githubusercontent.com/antiphysika/Initium/main/updates.json"
  #displayURL="https://github.com/antiphysika/Initium"
  #logoFile="Initium.png"
  #credits=""
  authors="${mod_authors}"
  description='''${mod_description}'''

#[[mixins]]
#config="${mod_id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies."${mod_id}"]]
  modId="neoforge"
  type="required"
  versionRange="${neo_version_range}"
  ordering="NONE"
  side="BOTH"

[[dependencies."${mod_id}"]]
  modId="minecraft"
  type="required"
  versionRange="${minecraft_version_range}"
  ordering="NONE"
  side="BOTH"

#
# vim: ts=2 sw=2 et fdm=marker :
